/**
 * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
 * `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
 * `pnpm run verify-persistence-catalog`, part of `doc-sync`).
 * @module @deepseek-ai/dsh-session/known-event-types
 */

/**
 * Every `SessionEventMap` member declared in this repository — the event
 * vocabulary this build understands. The persistence read path refuses to
 * interpret a log containing a type outside this set unless the event
 * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`
 * in `./types.ts`): such a log was likely written by a newer harness, and
 * silently skipping a required event would reconstruct a wrong session.
 * Downstream (out-of-repo) plugin events are outside this list by
 * construction; a registration surface for them is deferred until such a
 * consumer exists.
 */
/**
 * Event types a DEPLOYMENT registered at runtime (a product plugin's own
 * log-only records). The resume support check consults this beside the static
 * set, so a session written by the same composition loads even when an event
 * predates the writer stamping `ignorable: true`. Registration is
 * process-wide and additive on purpose: the composition that appends a type
 * is the composition that mounts the registering plugin.
 */
const RUNTIME_SESSION_EVENT_TYPES = new Set<string>()

/**
 * Teach this process one deployment-owned session event type.
 * @param type - the event type (e.g. `writerx/charge`).
 * @returns an unregister function (plugin unload).
 */
export function registerSessionEventType(type: string): () => void {
  RUNTIME_SESSION_EVENT_TYPES.add(type)
  return () => { RUNTIME_SESSION_EVENT_TYPES.delete(type) }
}

/**
 * Whether this process can interpret `type` — statically known, or registered
 * by the running composition.
 * @param type - the event type.
 * @returns true when a log carrying it may be reconstructed.
 */
export function isKnownSessionEventType(type: string): boolean {
  return KNOWN_SESSION_EVENT_TYPES.has(type) || RUNTIME_SESSION_EVENT_TYPES.has(type)
}

export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([
  'agent-preset/selected',
  'agent/inbox/spliced',
  'approval/asked',
  'approval/decided',
  'approval/policy',
  'assistant/chunk',
  'assistant/message',
  'command/done',
  'command/run',
  'compaction/end',
  'compaction/prune',
  'compaction/start',
  'compaction/summary',
  'feedback/record',
  'goal/change',
  'hook/invoked',
  'hook/result',
  'llm/retry',
  'llm/retry-started',
  'permission/preset',
  'plan/mode',
  'request/context',
  'request/header',
  'sandbox/mode',
  'schedule/change',
  'session/end-seed',
  'session/title',
  'session/title-llm-request',
  'step/end',
  'step/start',
  'subagent/descriptor',
  'todo/write',
  'tool-workflow/agent-end',
  'tool-workflow/agent-start',
  'tool-workflow/run-end',
  'tool-workflow/run-start',
  'tool/call',
  'tool/code-dispatch',
  'tool/code-dispatch-start',
  'tool/result',
  'turn/end',
  'turn/start',
  'user/message',
  'web/deepseek-search-llm-request',
])
