/**
 * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run
 * `pnpm run gen-persistence-catalog` to regenerate (verified fresh by
 * `pnpm run verify-persistence-catalog`, part of `doc-sync`).
 * @module @deepseek-ai/dsh-session/known-event-types
 */

/**
 * Deployment-owned event types registered by the running composition.
 * The persistence read path consults this set beside the static vocabulary
 * so the same composition can reopen records that predate an `ignorable`
 * marker. Registration lifetime follows the plugin that owns the event.
 */
const RUNTIME_SESSION_EVENT_TYPES = new Set<string>()

/**
 * Teach this process one deployment-owned session event type.
 * @param type - the event type (for example, `writerx/charge`).
 * @returns a disposer that removes the runtime registration.
 */
export function registerSessionEventType(type: string): () => void {
  RUNTIME_SESSION_EVENT_TYPES.add(type)
  return () => { RUNTIME_SESSION_EVENT_TYPES.delete(type) }
}

/**
 * Return whether this process can interpret a statically declared or runtime-registered event type.
 * @param type - the event type to inspect.
 * @returns whether a log carrying the type may be reconstructed.
 */
export function isKnownSessionEventType(type: string): boolean {
  return KNOWN_SESSION_EVENT_TYPES.has(type) || RUNTIME_SESSION_EVENT_TYPES.has(type)
}

/**
 * Every `SessionEventMap` member declared in this repository — the static
 * event vocabulary this build understands. The persistence read path
 * refuses a type outside this set and the runtime registry unless the event
 * carries the envelope's `ignorable` marker; silently skipping a required
 * event could reconstruct the wrong session.
 */
export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([
  'agent-preset/selected',
  'agent/inbox/spliced',
  'approval/asked',
  'approval/decided',
  'approval/policy',
  'assistant/chunk',
  'assistant/message',
  'command/done',
  'command/run',
  'compaction/end',
  'compaction/prune',
  'compaction/start',
  'compaction/summary',
  'feedback/record',
  'goal/change',
  'hook/invoked',
  'hook/result',
  'llm/retry',
  'llm/retry-started',
  'permission/preset',
  'plan/mode',
  'request/context',
  'request/header',
  'sandbox/mode',
  'schedule/change',
  'session/end-seed',
  'session/title',
  'session/title-llm-request',
  'step/end',
  'step/start',
  'subagent/descriptor',
  'team/member',
  'team/message/delivered',
  'team/message/queued',
  'team/task',
  'todo/write',
  'tool-workflow/agent-end',
  'tool-workflow/agent-start',
  'tool-workflow/run-end',
  'tool-workflow/run-start',
  'tool/call',
  'tool/code-dispatch',
  'tool/code-dispatch-start',
  'tool/result',
  'turn/end',
  'turn/start',
  'user/message',
  'web/deepseek-search-llm-request',
])
